version: '3.7'
services:
  api:
    build: .
    ports:
      - '3333:3333'
    env_file:
      - ./.env
    links:
      - redis
    depends_on:
      - db
      - redis
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=store_api
    volumes:
      - 'postgres-db:/data/store_api'
  redis:
    image: 'redis:alpine'
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
volumes:
  postgres-db:
  redis:
    driver: local
