version: "3"
services:
    api:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
        command: bash -c "yarn sequelize db:migrate && yarn dev"
